
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 18 15:18:05 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 30;
  public static final int GE = 25;
  public static final int SEMI = 35;
  public static final int LPAREN = 31;
  public static final int REPEAT = 6;
  public static final int INT = 16;
  public static final int FOR = 8;
  public static final int MINUS = 28;
  public static final int WRITE = 11;
  public static final int RPAREN = 32;
  public static final int AND = 19;
  public static final int LT = 24;
  public static final int OR = 20;
  public static final int BEGIN = 9;
  public static final int UNTIL = 7;
  public static final int NUM = 13;
  public static final int PLUS = 27;
  public static final int ASSIGN = 15;
  public static final int IF = 2;
  public static final int ID = 12;
  public static final int LE = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int RETURN = 37;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int VOID = 18;
  public static final int EQ = 21;
  public static final int TIMES = 29;
  public static final int ELSE = 4;
  public static final int READ = 10;
  public static final int BOL = 14;
  public static final int THEN = 3;
  public static final int NE = 22;
  public static final int LCORCHE = 33;
  public static final int RCORCHE = 34;
  public static final int END = 5;
  public static final int GT = 26;
}

